schema_version: 2.1
globals:
  ssl_mode: local-ca
  listen_ips:
  - 192.168.1.2
  - 192.168.99.2
  ports:
    http: 80
    https: 443
    http_extra: []
    https_extra: []
  ui:
    host: 192.168.1.1
    port: 63412
  stub:
    enabled: true
    root: /opt/var/www/stub
  acme:
    email: admin@crubs.store
apps:
- id: ha
  name: Home Assistant
  upstream:
    address: 192.168.99.12
    port: 8123
    scheme: http
- id: dns
  name: Nginx Manager
  upstream:
    address: 192.168.1.1
    port: 63412
    scheme: http
- id: plane
  name: Plane
  upstream:
    address: 192.168.99.15
    port: 443
    scheme: http
- id: proxmox-s1-dashboard
  name: Dashboard Proxmox [s1]
  upstream:
    address: 192.168.99.10
    port: 8006
    scheme: https
- id: proxmox-s2-dashboard
  name: Dashboard Proxmox [s2]
  upstream:
    address: 192.168.99.20
    port: 8006
    scheme: https
- id: zashboard
  name: Dashboard Mihomo
  upstream:
    address: 192.168.1.1
    port: 9090
    scheme: http
- id: xkeen-ui
  name: Dashboard XKeen
  upstream:
    address: 192.168.1.1
    port: 8088
    scheme: http
- id: vless-proxy
  name: Vless Proxy
  upstream:
    address: 192.168.99.18
    port: 25500
    scheme: http
hosts:
- host: ha.crubs.store
  kind: public
  app_id: ha
  verify_upstream_ssl: false
  ws_proxy:
    enabled: false
    path: /connections
    rewrite_to_wss: false
    rewrite_from: ''
  dns:
    publish:
    - local
    local_record_ip: auto
  tls:
    cert_policy: auto_local_ca
    cert_ref: auto
    san: []
  endpoints:
  - name: web
    listen:
      protocol: https
      port: 443
    behavior:
      redirect: https
- host: dns.local
  kind: private
  app_id: dns
  verify_upstream_ssl: false
  ws_proxy:
    enabled: false
    path: /connections
    rewrite_to_wss: false
    rewrite_from: ''
  dns:
    publish:
    - local
    local_record_ip: auto
  tls:
    cert_policy: auto_local_ca
    cert_ref: auto
    san: []
  endpoints:
  - name: web
    listen:
      protocol: https
      port: 443
    behavior:
      redirect: https
- host: plane.crub.store
  kind: public
  app_id: plane
  verify_upstream_ssl: false
  ws_proxy:
    enabled: false
    path: /connections
    rewrite_to_wss: false
    rewrite_from: ''
  dns:
    publish:
    - local
    local_record_ip: auto
  tls:
    cert_policy: auto_local_ca
    cert_ref: auto
    san: []
  endpoints:
  - name: web
    listen:
      protocol: https
      port: 443
    behavior:
      redirect: https
- host: proxmox.dashboard.local
  kind: private
  app_id: proxmox-s1-dashboard
  verify_upstream_ssl: false
  ws_proxy:
    enabled: false
    path: /connections
    rewrite_to_wss: false
    rewrite_from: ''
  dns:
    publish:
    - local
    local_record_ip: auto
  tls:
    cert_policy: auto_local_ca
    cert_ref: auto
    san: []
  endpoints:
  - name: web
    listen:
      protocol: https
      port: 443
    behavior:
      redirect: https
- host: s1.proxmox.dashboard.local
  kind: private
  app_id: proxmox-s1-dashboard
  verify_upstream_ssl: false
  ws_proxy:
    enabled: false
    path: /connections
    rewrite_to_wss: false
    rewrite_from: ''
  dns:
    publish:
    - local
    local_record_ip: auto
  tls:
    cert_policy: auto_local_ca
    cert_ref: auto
    san: []
  endpoints:
  - name: web
    listen:
      protocol: https
      port: 443
    behavior:
      redirect: https
- host: s2.proxmox.dashboard.local
  kind: private
  app_id: proxmox-s2-dashboard
  verify_upstream_ssl: false
  ws_proxy:
    enabled: false
    path: /connections
    rewrite_to_wss: false
    rewrite_from: ''
  dns:
    publish:
    - local
    local_record_ip: auto
  tls:
    cert_policy: auto_local_ca
    cert_ref: auto
    san: []
  endpoints:
  - name: web
    listen:
      protocol: https
      port: 443
    behavior:
      redirect: https
- host: zashboard.local
  kind: private
  app_id: zashboard
  verify_upstream_ssl: false
  ws_proxy:
    enabled: true
    path: /connections
    rewrite_to_wss: true
    rewrite_from: ws://192.168.1.1:9090
  dns:
    publish:
    - local
    local_record_ip: auto
  tls:
    cert_policy: 'off'
    cert_ref: none
    san: []
  endpoints:
  - name: web
    listen:
      protocol: http
      port: 80
    behavior:
      redirect: 'off'
- host: xkeen.local
  kind: private
  app_id: xkeen-ui
  verify_upstream_ssl: false
  ws_proxy:
    enabled: false
    path: /connections
    rewrite_to_wss: false
    rewrite_from: ''
  dns:
    publish:
    - local
    local_record_ip: auto
  tls:
    cert_policy: auto_local_ca
    cert_ref: auto
    san: []
  endpoints:
  - name: web
    listen:
      protocol: https
      port: 443
    behavior:
      redirect: https
- host: vless.sub.local
  kind: private
  app_id: vless-proxy
  verify_upstream_ssl: false
  ws_proxy:
    enabled: false
    path: /connections
    rewrite_to_wss: false
    rewrite_from: ''
  dns:
    publish:
    - local
    local_record_ip: auto
  tls:
    cert_policy: auto_local_ca
    cert_ref: auto
    san: []
  endpoints:
  - name: web
    listen:
      protocol: https
      port: 443
    behavior:
      redirect: https
certs: []
